Add Testing for the Add and Remove tasks
Danieldotcomcoder/TO-DO-LIST pull request #9
Opened 2021-11-04 08:57 UTC by Danieldotcomcoder

Added pure functions for Add and Remove tasks
Added tests to check the functionality of Add/Remove functions.
Added Mock HTML
Added Mock LocalStorage

To check The Tests type : npm start test in terminal .

2021-11-04 09:41 UTC, rloterh requested changes
Hi  Danny & Munsa, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦  🚦  

## Good Points 👍  
- Test cases are passings
- Test covers **add item** and **delete item** functions
- Tests are grouped using the `description()` method


## Required Changes ♻️
_Kindly check the comments under the review._

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-04 09:41 UTC, rloterh commented on src/__tests__/function.test.js
> +describe('Testing Adding and Removing tasks', () => {
- [ ] Other _pure functions_ in your code are **not tested** aside _add item_ and _delete item_. Kindly ensure to test **all** pure functions such as the _edit_, _complete: true/false_, _clear_ all completed_ and other created pure functions.

2021-11-04 09:41 UTC, rloterh commented on src/__tests__/function.test.js
> +
- [ ] There are some test cases that **failing**. Kindly ensure that all test cases are passing.

**Failing jest test:**
![image](https://user-images.githubusercontent.com/12745474/140291561-fffb76b1-a5ee-49f0-abf8-12ba0600e1fc.png)

2021-11-04 09:53 UTC, Danieldotcomcoder commented on src/__tests__/function.test.js
> +describe('Testing Adding and Removing tasks', () => {
Thank you , but in the requirments for this project we should test the add and delete item  only

2021-11-04 09:54 UTC, Danieldotcomcoder commented on src/__tests__/function.test.js
> +
Thank you , the tests are working on my side 
![image](https://user-images.githubusercontent.com/87448628/140293594-4a8adc55-1c31-43c6-8e01-0b7323ffcc15.png)

2021-11-04 12:33 UTC, Munsa1 commented on src/__tests__/function.test.js
> +
![Get Started - TO-DO-LIST - Visual Studio Code 11_4_2021 2_31_24 PM](https://user-images.githubusercontent.com/81932478/140313985-621eed28-fda1-4dcd-ad98-f2b3b2eae8dd.png)


It's working for me too.

2021-11-04 13:16 UTC, henatan99 requested changes
Hi @Danieldotcomcoder , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-04 13:16 UTC, henatan99 commented on src/__tests__/function.test.js
> +describe('Testing Adding and Removing tasks', () => {
- [ ] May not be exactly as the previous reviewer suggests, but you need to add tests for all functions related to adding and removing items. I can see you have used pure functions as mock functions for the unit tests. But the requirement says you should use mock functions for localStorage and DOM. I suggest you import the original 'createNewTodo` and `deleteTodo` functions from `managelists.js` module file into the test file and use localStorage and DOM mock functions. For your reference I put a section of the requirements below:

```
Some of those functions however will update localStorage and manipulate the DOM. For those, you will need to use mocks:
- Mock a storage object to "imitate" localStorage operations.
- Mock HTML to test if add/delete functions add or remove exactly one <li> element to/from the list in the DOM.
```

2021-11-05 09:18 UTC, henatan99 approved these changes
Hi @Danieldotcomcoder , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-24 13:48 UTC, closed without merging